### ISSUE TITLE
Create pomodoro command

### ISSUE THREAD

**Issue by iamericfletcher** [discoRd-org/discoRd-bot#19]
Create a **$pomodoro** command with optional arguments to use in the Study Hall channels. 

**$pomodoro start**

- Initializes a 25 minute timer. 
- Every 5 minutes a message is posted letting the user(s) know how much time is remaining. 

**$pomodoro pause**

- Pauses the timer.

**$pomodoro end**

- Ends the timer.

**$pomodoro remaining**

- Sends a message with remaining time (e.g. "There is 10 minutes and 35 seconds remaining. Keep it up!")

**Additional considerations:**

- Can multiple timers be running at the same time within the same channel? Should we limit it somehow? 
- Should statistics be tracked like **total focus time** or **total number of pomodoros** etc?

**Comment by acylam** [comment]
By Study Hall, do you mean the R-help channels?

**Comment by iamericfletcher** [comment]
Yes, the R-help channels that are located within the Study Hall category.

**Comment by acylam** [comment]
Those are voice channels though. How would you post messages there?
